Feat/gam 32
Olovyannikov/middle.gamedev.praktikum.yandex pull request #24
Opened 2023-12-03 12:07 UTC by eNRja

### Добавил FullScreen Api 

### Скриншоты
![Screenshot 2023-12-03 150557](https://github.com/Olovyannikov/middle.gamedev.praktikum.yandex/assets/117164155/e2f13377-1d58-429b-8004-d6d74de61b07)
![Screenshot 2023-12-03 150619](https://github.com/Olovyannikov/middle.gamedev.praktikum.yandex/assets/117164155/9687528f-37fe-4a2b-beea-77d2b54d56b8)

### TBD (если есть)

2023-12-03 12:09 UTC, Olovyannikov commented
У тебя снова тянутся все коммиты, которые не принадлежат этой задаче. Поправь, пожалуйста :)

2023-12-03 12:14 UTC, Olovyannikov commented on packages/client/src/entities/FullScreen/FullScreen.module.scss
> +    background-image: url('../../app/assets/img/fullscreen_icon.svg');
Вложи иконку в кнопку как компонент

2023-12-03 12:14 UTC, Olovyannikov commented on packages/client/src/entities/FullScreen/index.tsx
> +        !documentTyped.fullscreenElement &&
`const isFullscreen = documentTyper.fullscreenElement`;
`if (!isFullscreen) {}`

2023-12-03 12:14 UTC, Olovyannikov commented on packages/client/src/entities/FullScreen/index.tsx
> +    useEffect(() => {
Создай кастомный хук useFullscreenApi в каталоге`shared/hooks`

2023-12-03 12:14 UTC, Olovyannikov commented on packages/client/src/entities/FullScreen/index.tsx
> +    useEffect(() => {
Потом сюда тяни как `useFullscreen()`;

2023-12-03 12:14 UTC, Olovyannikov commented on packages/client/src/entities/FullScreen/index.tsx
> +            onClick={() => toggleFullscreen()}
`onClick={toggleFullscreen}`

2023-12-03 12:14 UTC, Olovyannikov commented on packages/client/src/entities/FullScreen/index.tsx
> +function toggleFullscreen(elem?: FullScreenableElement): void {
Вынести в shared/utils

2023-12-03 19:57 UTC, IvanPeleshok commented on packages/client/src/shared/hooks/useFullScreenAPI.tsx
> +    } else {
Для минимизации ветвления можно писать следующие конструкции (это сильно облегчает чтение кода):
```
if (var1) {
  ...
  return
} 

// else
```

2023-12-03 20:02 UTC, IvanPeleshok commented on packages/client/src/shared/utils/toggleFullScreen.ts
> +export function toggleFullscreen(elem?: FullScreenableElement): void {
А где используется данный хелпер? 

Судя по коду, в кастомном хуке используется другая функция для реализация полноэкранного режима
<img width="881" alt="image" src="https://github.com/Olovyannikov/middle.gamedev.praktikum.yandex/assets/70073003/44bb8434-c6dd-443a-8668-6f818176c323">


Предлагаю не писать функции, которые не используются и выбрать что-то одно
Данный функционал с поддержкой кроссбраузерности, предлагаю выбрать его для использования в хуке

2023-12-03 20:06 UTC, IvanPeleshok requested changes
Проделана большая работа!
Отлично потрудились!

Есть некоторые вопросы, видимо нужна небольшая доработка

Оставил комментарии по улучшению реализации фичи

Обязательно покажите работу своей команде, нужен минимум один апрув от вашей команды

Хорошего дня :)

2023-12-04 18:26 UTC, Olovyannikov approved these changes

2023-12-04 18:26 UTC, Olovyannikov commented on packages/client/src/entities/FullScreen/index.tsx
> +            <Icon src={!isFullscreen ? FullScreenIcon : FullScreenExitIcon} />
Можешь обойтись без компонента Icon
Просто добавь <FullScreenIcon /> 
Если ts ругается, то нагугли how to paste svg into react

2023-12-04 18:26 UTC, Olovyannikov commented on packages/client/src/shared/hooks/useFullScreenAPI.tsx
> +export const useFullScreenAPI = () => {
Выглядит супер!

2023-12-04 18:26 UTC, Olovyannikov commented on packages/client/src/shared/ui/Icon/index.tsx
> +import React from 'react';
Импорт реакта с 17-ой версии не нужен

2023-12-04 19:25 UTC, IvanPeleshok approved these changes
Проделана большая работа!
Отлично потрудились!

Работа не имеет критических замечаний
Поздравляю, апрув 🚀 

Хорошего дня :)

2023-12-05 09:29 UTC, merged