[WIP] feat(forum-client): add Forum service (GAM-47)
Olovyannikov/middle.gamedev.praktikum.yandex pull request #35
Opened 2024-01-07 09:07 UTC by Olovyannikov

### Какую задачу решаем
Поддержать API форума на клиенте

### Скриншоты/видяшка (если есть)

### TBD (если есть)
// wait for backend api

2024-01-16 18:54 UTC, Olegas requested changes
Добрый день. 
Замечания детально расписал в комментариях, тут в общем виде
1. Использование useToggle очень спорное, считаю что надо переделать (почему - подробно в комментариях)
2. Многократно повторяется cn(s.xxx) - можно заменить на s.xxx
3. Многократно повторяется использование объекта, обяъвленного "по месту" в свойстве sx - ведет к потенциальным лишним перерисовкам
Это надо исправить.

Дополнительно: очень много изменений, НЕ относящихся к задаче. Какая-то часть из них видимо вызвана мержем с dev - не надо так делать. Такие PR сложно проверять, приходится продираться через кучу нерелевантных изменений. Это уже оставим как есть, но на будущее лучше так не делать

2024-01-16 18:54 UTC, Olegas commented on packages/client/src/entities/CreateForumTopic/index.tsx
> +                setIsErrorSnackbarOpen();
Выглядит как очень странная затея. Этот set совсем даже не set а toggle ([документация](https://usehooks-ts.com/react-hook/use-toggle)). Это из кода не читается, надо импорт смотреть. Надо это переименовать соответственно. Вторая проблема - тогл он же переключает состояние на противоположное. А тут явно нужно выставить в состояние true (показать ошибку). Крайне неудачное решение использовать toggle для таких вещей как ошибки или модалки

2024-01-16 18:54 UTC, Olegas commented on packages/client/src/entities/UserInfo/index.tsx
> +    console.log({ isAuth });
Отладочный вывод. Не надо его оставлять в продакшен-коде

2024-01-16 18:54 UTC, Olegas commented on packages/client/src/entities/UserInfo/index.tsx
> +        <Container className={cn(s.info)}>
cn тут явно лишний, достаточно просто s.info

2024-01-16 18:54 UTC, Olegas commented on packages/client/src/features/CreateComment/index.tsx
> +                        sx={{ width: '100%' }}
Вот эти объекты со стилями - они создаются новые на каждый рендер и вызывают перерисовку компонента. Они не меняются, их можно смело вынести за рамки компонента

2024-01-16 18:54 UTC, Olegas commented on packages/client/src/features/CreateTopic/index.tsx
> +const style = {
Вот тут со стилем правильно сделано.

2024-01-16 18:54 UTC, Olegas commented on packages/client/src/features/UploadAvatar/index.tsx
> +        file && setPreviewAvatar(URL.createObjectURL(file));
А как может быть что тут нет file? Выше же проверка есть...

2024-01-16 18:54 UTC, Olegas commented on packages/client/src/features/UploadAvatar/index.tsx
> +        <Form id='avatarForm' className={cn(s.root)} onSubmit={handleSubmitAvatar}>
Еще лишний cn

2024-01-17 03:34 UTC, Olovyannikov commented on packages/client/src/entities/CreateForumTopic/index.tsx
> +                setIsErrorSnackbarOpen();
Поправил

2024-01-17 03:35 UTC, Olovyannikov commented on packages/client/src/entities/UserInfo/index.tsx
> +    console.log({ isAuth });
Поправил, спасибо

2024-01-17 03:37 UTC, Olovyannikov commented on packages/client/src/entities/UserInfo/index.tsx
> +        <Container className={cn(s.info)}>
cn убрал во всех местах, где он избыточен

2024-01-17 03:39 UTC, Olovyannikov commented on packages/client/src/features/CreateComment/index.tsx
> +                        sx={{ width: '100%' }}
Согласен, вынес за пределы компонента

2024-01-17 03:40 UTC, Olovyannikov commented on packages/client/src/features/UploadAvatar/index.tsx
> +        file && setPreviewAvatar(URL.createObjectURL(file));
Действительно, проверка есть. Убрал лишнюю проверку

2024-01-17 17:53 UTC, Olegas approved these changes
Работу принимаю, но обратите внимание - не все вхожждения useToggle были исправлены. Либо замените их на state, либо хотя бы переименуйте что бы было понятно что происходит.

2024-01-17 18:32 UTC, tinymelon commented
В ПР действительно попало много каких-то правок по синтаксису, из-за чего тяжело искать среди них реализацию фичей. Кстати, у Евгения было то же самое, кажется, что-то не то случилось потому что раньше такого не было. Ну а по сути всё хорошо

2024-01-17 18:34 UTC, tinymelon approved these changes
Много правок по синтаксису попало в ПР, но по сути всё хорошо

2024-01-17 18:35 UTC, merged